Dev
go-park-mail-ru/2019_2_IBAT pull request #5
Opened 2019-09-27 20:24 UTC by yourKriptonite

the first working  backend version

2019-09-27 20:47 UTC, SinimaWath requested changes

2019-09-27 20:47 UTC, SinimaWath commented on internal/pkg/auth/auth_storage.go
> +	. "hh_workspace/2019_2_IBAT/internal/pkg/interfaces"
Давай не хранить интерфесы в отдельном месте. Храни интерфейсы в пакете с реализацией. К примеру, посмотри вот гошный пакет io https://golang.org/src/io/ разве они вынесли интерфейсы куда-то?

2019-09-27 20:47 UTC, SinimaWath commented on internal/pkg/auth/auth.go
> +		log.Printf("No such session")
Формируй читабельный ответ с понятным кодом ошибки, здесь это 404. Исправь это везде в других местах тоже

2019-09-27 20:47 UTC, SinimaWath commented on internal/pkg/auth/auth.go
> +func (h *Handler) DeleteSession(cookie *http.Cookie) bool {
А там у хэндлеров разве не такой интерфейс?
`(w http.ResponseWriter, r *http.Request)`
Какой код это позволяет делать?

2019-09-27 20:47 UTC, SinimaWath commented on internal/pkg/auth/auth.go
> +	h.Storage.Delete(cookie.Value)
А проверить, что мы смогли удалить сессию или нет?

2019-09-27 20:47 UTC, SinimaWath commented on internal/pkg/auth/auth.go
> +	authInfo, _ := h.Storage.Get(cookieValue) //impossible error, should use only Set method
Зачем это? Возвращай в cookieValue Expires

2019-09-27 20:47 UTC, SinimaWath commented on internal/pkg/auth/auth.go
> +	bytes, err := ioutil.ReadAll(body)
А закрыть тело?

2019-09-27 22:14 UTC, yourKriptonite commented on internal/pkg/auth/auth_storage.go
> +	. "hh_workspace/2019_2_IBAT/internal/pkg/interfaces"
сначала не выносил, но потом получил зацикленное включение модулей, когда auth подключал к users и наоборот, поэтому решил вынести

2019-09-28 20:15 UTC, yourKriptonite commented on internal/pkg/auth/auth.go
> +		log.Printf("No such session")
ответ формируется в хэндлере

2019-09-28 20:46 UTC, yourKriptonite commented on internal/pkg/auth/auth.go
> +	bytes, err := ioutil.ReadAll(body)
тело закрывается в хэндлере

2019-09-28 20:46 UTC, yourKriptonite commented on internal/pkg/auth/auth.go
> +	bytes, err := ioutil.ReadAll(body)
внешнем
нэйминг изменил

2019-09-28 20:46 UTC, yourKriptonite commented
осталось сделать отдачу аватарок

2019-09-28 20:47 UTC, yourKriptonite commented
сервер задеплоил

2019-10-01 19:07 UTC, merged